{
    'name': "HR Military Employee Rewards",
    'author': 'Yevhen Babii',
    'category': 'HR',
    'summary': """Employees rewards""",
    'website': '',
    #'company': 'Botspot Infoware Pvt. Ltd.',
    #'maintainer': 'Botspot Infoware Pvt. Ltd.',
    'description': """ Configure Employee Rewards """,
    'version': '14.0',
    'depends': [''],
    'data': [
              'security/ir.model.access.csv',
              #'wizard/employee_reward_wizard_view.xml',
              'views/employee_badge_configuration_view.xml',
              'views/hr_employee_view.xml',
              'data/data.xml',
              'reports/employee_certificate_report_template.xml',
            ],
    'license': 'Other proprietary',
    'installable': True,
    'auto_install': False,
}
